# Generated by Django 4.1.6 on 2023-02-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://bitsofco.de/content/images/2018/12/Screenshot-2018-12-16-at-21.06.29.png'),
        ),
    ]
