# Generated by Django 4.1.6 on 2023-02-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_history',
        ),
        migrations.DeleteModel(
            name='Price_History',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriceHistoryProduct', to='Tracker.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_history',
            field=models.ManyToManyField(related_name='PriceHistoryProduct', to='Tracker.pricehistory'),
        ),
    ]
