# Generated by Django 4.1.6 on 2023-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_alter_pricehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='domain',
            field=models.CharField(default='', max_length=50),
        ),
    ]
